
<?php $this->headScript()->appendFile( Anta_Core::getBase() . '/js/jquery.pinger.js', 'text/javascript' ); ?>
<?php $this->headScript()->appendFile( Anta_Core::getBase() . '/js/jquery-toastmessage.js', 'text/javascript' ); ?>
<?php $this->headScript()->appendFile( Anta_Core::getBase() . '/js/jquery.color.js', 'text/javascript' ); ?>


<!-- left menu -->
<?php
	$this->headLink()->appendStylesheet( Anta_Core::getBase() . '/css/today-special.css');
	
	
	echo 
	Ui_Board::getInstance( "Documents", array( 
		'user'		=> $this->user
	));
?>

	
<!-- documents list content -->
<?php echo $this->dock; ?>
<!-- documents list content -->
<!-- script recursive for document-status -->

<!-- tipsy king  css-->
<?php $this->headLink()->appendStylesheet( Anta_Core::getBase() . '/css/tipsy.css'); ?>
	
<!-- ui toast -->
<?php	$this->headLink()->appendStylesheet( Anta_Core::getBase() . '/css/jquery.toastmessage.css');	?>
<script type="text/javascript">
		// user configuration of all toastmessages to come:
		$().toastmessage({
			stayTime: 7500
		});
</script>
<!-- endof ui toast -->

<style type=""text/css">
	.crawl-action img{
		cursor: pointer
	}
</style>

<!-- crawls namespace -->                 
<script type="text/javascript">
	var crawls = {
		urls:{
			'remove': "<?=ANTA_URL?>/api/crawls-remove",
			'add'	: "<?=ANTA_URL?>/api/crawls-add",
			'list'	: "<?=ANTA_URL?>/api/crawls"
		},
		pinger: null // the pinger instance which update the list
	};
	
	/**
	 * use this function to create the row.
	 * @param crawl 	- the json object of the crawl
	 * @return void
	 */
	crawls.create = function( crawl ){
		console.log( crawl );
		$("#craft-content-google").prepend(
			$("<div/>", {'class':'grid_24 alpha omega item', 'id':'gr_'+crawl.id_crawl}).append(
				'<div class="grid_1 prefix_1 alpha centered crawl-action">' +
					'<img onclick="crawls.remove( ' + crawl.id_crawl + ')" src="/anta_dev/images/cross-small.png">'+	
				'</div>'+
				'<div class="grid_1" id="gr_3_id">'+crawl.id_crawl+'</div>' + 
				'<div class="grid_6" id="gr_3_start_words">'+crawl.start_words+'</div>' +
				'<div class="grid_4" id="gr_3_date">'+crawl.creation_date + '</div>' +
				'<div class="grid_4" id="gr_3_status">'+crawl.status+'</div>' +
				'<div class="grid_4" id="gr_3_desc"><a href="/anta_dev/api/crawl-download/id/'+crawl.id_crawl+'">gexf</a></div>'
			).css({'display':'none','background-image':'none', "background":'gold'}).show("fast").animate({backgroundColor: "transparent"}, 800)
		);
		
	}
	
	crawls.addHandler = function( result ){
		console.log( "addHandler", result );
	}
	
	crawls.add = function( form ){
		
		$.ajax({ url: crawls.urls.add, dataType: 'json', success:crawls.addHandler, data:{id: id}, error:function(data){console.log(data)}});	
	}
	
	crawls.init = function(){
		crawls.pinger = new pinger({named:'crawls', url: crawls.urls.list, success:crawls.updateHandler, timeOut:2000, clearTimeoutOnError: false});
		// $("#craft-google .item ").click( function( event ){event.currrent} );
	}
	
	crawls.removeHandler = function( result ){
		console.log("crawls.removeHandler", result);
		if( result.status != "ok" ){
			$().toastmessage('showErrorToast', "error, <br/>" +result.error );
			return;
		}
		$().toastmessage('showSuccessToast', " crawl <b>"+crawl.start_words+"</b> has been removed as requested." );
		crawls.hide("gr_" +result.crawl.id_crawl);
		
	}
	
	crawls.hide = function( item_id ){
		$( "#"+item_id ).hide( "fast" );
	}
	
	crawls.remove = function( id ){
		$.ajax({ url: crawls.urls.remove, dataType: 'json', success:crawls.removeHandler, data:{id: id}, error:function(data){console.log(data)}});
	}
	
	crawls.update = function( id, status ){
		$( "#gr_" + id + "_status" ).text( status );
	}
	
	crawls.updateHandler = function( result ){
		
		if( result.status != "ok"){
			console.log(result.error);
			return;
		}
		
		for ( var i in result.crawls ){
			crawl = result.crawls[i];
			c = $( "#gr_" + crawl.id_crawl );	
			if( c.length ){
				crawls.update( crawl.id_crawl, crawl.status );
				continue;
			}
			crawls.create( crawl );
		}
  	
		// discard from viz
		$(".item").each( function( index, event){
			
			var id = $(event).attr( 'id' );
			
			var found = false;
			for ( var i in result.crawls ){
				// console.log( "gr_" + result.crawls[i].id_crawl, id );
				if( "gr_" + result.crawls[i].id_crawl == id ){
					found = true;
					break;
					
				}
				
			};
			if( found == false ){
				crawls.hide( id );
			}
		});
		
	}
	
	
	$(document).ready( function(){
		crawls.init();	
	});
	
</script>