<?php
  /** css basic stylesheet */
  $this->headLink()->appendStylesheet( Anta_Core::getBase().'/css/reset.css');
  //$this->headLink()->appendStylesheet(  Anta_Core::getBase().'/css/960.fluid.css');
  $this->headLink()->appendStylesheet(  Anta_Core::getBase().'/css/960.css');
  // $this->headLink()->appendStylesheet( Anta_Core::getBase().'/css/fonts.css');
  $this->headLink()->appendStylesheet(  Anta_Core::getBase().'/css/style.css');
  
  $this->headScript()->appendFile(  Anta_Core::getBase().'/js/jquery-1.5.1.min.js');
   
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Actor Network Text Analyser</title>
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo  Anta_Core::getBase() ?>/favicon.ico">

  <?php echo $this->headLink() ?>
  <?php echo $this->headScript() ?>

</head>
<body>
  <?php if (Zend_Auth::getInstance()->hasIdentity() ): ?>
  <div id="main-search-field">
	<?php $user = Zend_Auth::getInstance()->getIdentity() ?>
    <form action="<?php echo Anta_Core::getBase()."/search/regexp/user/".$user->cryptoId ?>" method="POST">
		<input type="text" class="width_4" name="query">
		<input type="image" src="<?php echo Anta_Core::getBase()?>/images/magnifier.png">
	</form>
  </div>
  <?php endif; ?>
  <div class="wrapper">
	<div id="blackrow">&nbsp;</div>
	<div id="logo"><img src="<?php echo ANTA_URL ?>/images/anta-logo.png" alt="anta"><!--<h1>ANta</h1>--></div>
	<div id="notifications" class="container_24"><?php echo Application_Model_Ui_Boards_NotificationBoard::getInstance() ?></div>
	<div id="identity"><div class="container_24"><?php echo Application_Model_Ui_Boards_IdentityBoard::getInstance() ?></div></div>
	<div class="container_24">
	  <?php echo $this->layout()->content; ?>
	  <div class="push grid_24 alpha omega"></div>
	</div>
	
  </div>
  
  <div class="footer container_24"> 
	<div id="footer" class="grid_24 alpha omega"> 
	   
		
		<div class="grid_16 alpha" style="text-align:left; padding-top:9px; vertical-align:top">
			<div class="grid_10 alpha">
			<a href="http://medialab.sciences-po.fr/" target="_blank" title="Sciences Po ¦ Medialab"> 
				<img src="<?php echo ANTA_URL ?>/images/Sc-Po-Medialab-Gris.png" alt="Sciences Po ¦ Medialab"/> 
			</a>
			</div>
			<div class="grid_6 omega">
			<a href="http://www.densitydesign.org/" target="_blank" title="Density Design"> 
				<img src="<?php echo ANTA_URL ?>/images/logo dd.png"> 
			</a> 
			</div>
		</div> 
		<div class="grid_8 omega" style="text-align:left; padding-top:9px"> 
			<div class="grid_3 alpha omega margin_1" style="text-align:left">
				<a href="http://opencalais.com" class="margin_1">OpenCalais</a>
				<br> - Thomson Reuters - text analysis remote service
			</div>
			<div class="grid_3 alpha omega margin_1" style="text-align:left">
				<a href="http://achemiapi.com" class="margin_1">Alchemy API</a>
				<br> text analysis remote service
			</div>
		</div> 
	</div> 
  </div> 
  

</body>
</html>
